### ISSUE TITLE
RuntimeError: affine matrix of all images should be the same for channel-wise concatenation.

### ISSUE THREAD

**Issue by raise0915** [MICLab-Unicamp/medpseg#5]
Hello,

Thank you for publishing such a wonderful software.
When I use medpseg without GUI, the segmentation failed as shown.

```
Performing lobe segmentation pipeline...
Traceback (most recent call last):
  File "medpseg/.venv/lib/python3.8/site-packages/medpseg/pipeline.py", line 218, in pipeline
    lobe_dict = lober.predict(run, cpu=cpu)
  File "medpseg/.venv/lib/python3.8/site-packages/medpseg/lober_monai.py", line 94, in predict
    reference = self.loader({"image": image_path})
  File "medpseg/.venv/lib/python3.8/site-packages/monai/transforms/io/dictionary.py", line 162, in __call__
    data = self._loader(d[key], reader)
  File "medpseg/.venv/lib/python3.8/site-packages/monai/transforms/io/array.py", line 282, in __call__
    img_array, meta_data = reader.get_data(img)
  File "medpseg/.venv/lib/python3.8/site-packages/monai/data/image_reader.py", line 618, in get_data
    _copy_compatible_dict(metadata, compatible_meta)
  File "medpseg/.venv/lib/python3.8/site-packages/monai/data/image_reader.py", line 128, in _copy_compatible_dict
    raise RuntimeError(
RuntimeError: affine matrix of all images should be the same for channel-wise concatenation. Got [[  -0.9765625    0.           0.         249.5117   ]
 [   0.          -0.9765625    0.         249.5117   ]
 [   0.           0.           1.        -215.9      ]
 [   0.           0.           0.           1.       ]] and [[  -0.9765625    0.           0.         249.5117   ]
 [   0.          -0.9765625    0.         249.5117   ]
 [   0.           0.           1.        -212.9      ]
 [   0.           0.           0.           1.       ]].
ERROR: RuntimeError: affine matrix of all images should be the same for channel-wise concatenation. Got [[  -0.9765625    0.           0.         249.5117   ]
 [   0.          -0.9765625    0.         249.5117   ]
 [   0.           0.           1.        -215.9      ]
 [   0.           0.           0.           1.       ]] and [[  -0.9765625    0.           0.         249.5117   ]
 [   0.          -0.9765625    0.         249.5117   ]
 [   0.           0.           1.        -212.9      ]
 [   0.           0.           0.           1.       ]].
Aborting processing! This was most likely an error regarding the data input or missing weights before doing pip install.
Feel free to create an issue in our GitHub.
Closing worker thread...
Done.
```

Sementation is always suceeded when I use medpseg with GUI.

Would you have any pointers?
Thank you.

**Comment by dscarmo** [comment]
Sorry for taking a long time to answer, you probably disabling the lobe segmentation when using the GUI. Try to disable the lobe segmentation using the CLI argument --disable_lobe when using CLI and it should work. 

The loading pipeline for the lobe segmentation part is different and is causing that problem. In the future we will update the lobe segmentation model and fix that issue.

**Comment by raise0915** [comment]
Dear dscarmo,

Thank you for your comment and adding --disable_lobe worked well.
Looking forward to next updating:)
